# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.scss, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
Rails.application.config.assets.precompile += %w( filterrific/filterrific-spinner.gif )

Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( carts_articles.css )
Rails.application.config.assets.precompile += %w( categories.css )
Rails.application.config.assets.precompile += %w( clients.css )
Rails.application.config.assets.precompile += %w( flexslider.css )
Rails.application.config.assets.precompile += %w( home.css )
Rails.application.config.assets.precompile += %w( ion.rangeSlider.css )
Rails.application.config.assets.precompile += %w( ion.rangeSlider.skinHTML5.css )
Rails.application.config.assets.precompile += %w( ionicons.min.css )
Rails.application.config.assets.precompile += %w( memenu.css )
Rails.application.config.assets.precompile += %w( modal.css )
Rails.application.config.assets.precompile += %w( normalize.css )
Rails.application.config.assets.precompile += %w( owl.carousel.css )
Rails.application.config.assets.precompile += %w( owl.theme.css )
Rails.application.config.assets.precompile += %w( past_purchases.css )
Rails.application.config.assets.precompile += %w( shopping_carts.css )
Rails.application.config.assets.precompile += %w( sky-forms.css )
Rails.application.config.assets.precompile += %w( sky-forms-green.css )
Rails.application.config.assets.precompile += %w( articles.css )

Rails.application.config.assets.precompile += %w( bootstrap.-collapse.js )
Rails.application.config.assets.precompile += %w( bootstrap-tab.js )
Rails.application.config.assets.precompile += %w( bootstrap-transition.js )
Rails.application.config.assets.precompile += %w( imagezoom.js )
Rails.application.config.assets.precompile += %w( ion.rangeSlider.min.js )
Rails.application.config.assets.precompile += %w( jquery.easydropdown.js )
Rails.application.config.assets.precompile += %w( jquery.flexislider.js )
Rails.application.config.assets.precompile += %w( jquery.placeholder.js )
Rails.application.config.assets.precompile += %w( memenu.js )
Rails.application.config.assets.precompile += %w( modal.js )
Rails.application.config.assets.precompile += %w( owl.carousel.js )
Rails.application.config.assets.precompile += %w( owl.carousel.min.js )
Rails.application.config.assets.precompile += %w( responsiveslides.min.js )
Rails.application.config.assets.precompile += %w( simpleCart.min.js )
Rails.application.config.assets.precompile += %w( sky-forms-ie8.js )
Rails.application.config.assets.precompile += %w( sliderfunction.js )

Rails.application.config.assets.precompile += %w( 11.png )
Rails.application.config.assets.precompile += %w( 100.png )
Rails.application.config.assets.precompile += %w( 362.png )
Rails.application.config.assets.precompile += %w( AjaxLoader.png )
Rails.application.config.assets.precompile += %w( arrow.png )
Rails.application.config.assets.precompile += %w( av.png )
Rails.application.config.assets.precompile += %w( av-color.png )
Rails.application.config.assets.precompile += %w( banner1.png )
Rails.application.config.assets.precompile += %w( banner2.png )
Rails.application.config.assets.precompile += %w( banner3.png )
Rails.application.config.assets.precompile += %w( cart-1.png )
Rails.application.config.assets.precompile += %w( cart-2.png )
Rails.application.config.assets.precompile += %w( cart-3.png )
Rails.application.config.assets.precompile += %w( cart-11.png )
Rails.application.config.assets.precompile += %w( cart-22.png )
Rails.application.config.assets.precompile += %w( cart-33.png )
Rails.application.config.assets.precompile += %w( cd-remove-item.svg )
Rails.application.config.assets.precompile += %w( close.png )
Rails.application.config.assets.precompile += %w( close-hover.png )
Rails.application.config.assets.precompile += %w( concrete.png )
Rails.application.config.assets.precompile += %w( cover1.png )
Rails.application.config.assets.precompile += %w( cover1_1.png )
Rails.application.config.assets.precompile += %w( cover2.png )
Rails.application.config.assets.precompile += %w( crossword.png )
Rails.application.config.assets.precompile += %w( ddarrow.png )
Rails.application.config.assets.precompile += %w( down_arrow_select.jpg )
Rails.application.config.assets.precompile += %w( down_arrow_select.png )
Rails.application.config.assets.precompile += %w( grabbing.png )
Rails.application.config.assets.precompile += %w( logo.png )
Rails.application.config.assets.precompile += %w( s-icons.png )
Rails.application.config.assets.precompile += %w( search.png )
Rails.application.config.assets.precompile += %w( shop_akcija.png )
Rails.application.config.assets.precompile += %w( shop_slika.png )
Rails.application.config.assets.precompile += %w( slika1.png )
Rails.application.config.assets.precompile += %w( slika1trans.png )
Rails.application.config.assets.precompile += %w( slika1trans50.png )
Rails.application.config.assets.precompile += %w( slika2.png )
Rails.application.config.assets.precompile += %w( slika-boja.png )
Rails.application.config.assets.precompile += %w( slika-boja2.png )
Rails.application.config.assets.precompile += %w( slika-kateg.jpg )
Rails.application.config.assets.precompile += %w( star.png )
Rails.application.config.assets.precompile += %w( tick.png )
Rails.application.config.assets.precompile += %w( Untiled-1-Recoverd_Recoverd.psd )
Rails.application.config.assets.precompile += %w( ban1.jpg )
Rails.application.config.assets.precompile += %w( ban2.jpg )
Rails.application.config.assets.precompile += %w( ban3.jpg )




