test: &default

  # Credentials for REST APIs
  client_id: AVFjW9kpVD5ad8Pyn2FycgHbU3LmcCksKSH-05xnO4a504ay5lo-kGZJNKVXi77I0y5E6oiCoFvsCX0J
  client_secret: ECSWsgugLleg4p1tnWaDmJ4edJ0Gk0nf4gFpxMbZVQwLfC4-UXr4B_KQL6lm2VJgYoJZh8TO9SFQR7Bh

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: filipkapusta1@gmail.com
  password: filipjepeder2
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: filipkapusta1-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
